[workspace]
members = [
    "crates/compute",
    "crates/runtime",
    "crates/physics",
    "crates/ml",
    "crates/rl",
]
resolver = "2"

[workspace.dependencies]
naga = { version = "0.19", features = ["wgsl-in"] }

[workspace.dev-dependencies]
criterion = "0.5" 
