[workspace]
members = [
    "crates/compute",
    "crates/runtime",
    "crates/physics",
    "crates/ml",
    "crates/render",
    "crates/phenotype",
]
resolver = "2"

[workspace.dependencies]
naga = { version = "0.19", features = ["wgsl-in"] }

