[workspace]
resolver = "2"
members = [
    "jaxs",
    "crates/compute",
    "crates/ml",
    "crates/phenotype",
    "crates/physics",
    "crates/render",
]
exclude = [
    "docs"
]

[workspace.dependencies]
naga = { version = "0.19", features = ["wgsl-in"] }

