[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19.4"
winit = "0.29.15"
anyhow = "1.0.86"
pollster = "0.3.0"
bytemuck = { version = "1.15.0", features = ["derive"] }
physics = { path = "../physics" }
glam = { version = "0.24", features = ["bytemuck"] }
