[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19"
winit = "0.29"
anyhow = "1.0"
pollster = "0.3"
bytemuck = { version = "1.12", features = ["derive"] }
physics = { path = "../physics" }
