[package]
name = "rl"
version = "0.1.0"
edition = "2021"

[dependencies]
ml = { path = "../ml" }
physics = { path = "../physics" }

[dev-dependencies]
criterion = "0.5"
sysinfo = "0.35"

[[bench]]
name = "ppo"
harness = false
